import React from 'react';
import { IconType } from './IconEnum';
import {
  HomeRounded,
  PeopleAltRounded,
  ForumRounded,
  FlagRounded,
  SettingsRounded,
  NotificationsNone,
  ArrowDropDown,
  VisibilityOutlined,
  Send,
  EmailOutlined,
  LockOutlined,
  PersonOutline,
  ExitToApp,
  Favorite,
  ArrowBackIos,
  CloudUploadOutlined,
  CheckCircleOutline,
  CancelOutlined,
} from '@material-ui/icons';

export const icons: Record<IconType, JSX.Element> = {
  [IconType.Groups]: <PeopleAltRounded />,
  [IconType.Home]: <HomeRounded />,
  [IconType.Help]: <FlagRounded />,
  [IconType.Messager]: <ForumRounded />,
  [IconType.Settings]: <SettingsRounded />,
  [IconType.Notifications]: <NotificationsNone />,
  [IconType.Arrow]: <ArrowDropDown />,
  [IconType.Views]: <VisibilityOutlined />,
  [IconType.Send]: <Send />,
  [IconType.Email]: <EmailOutlined />,
  [IconType.Lock]: <LockOutlined />,
  [IconType.User]: <PersonOutline />,
  [IconType.Exit]: <ExitToApp />,
  [IconType.Like]: <Favorite />,
  [IconType.CloseArrow]: <ArrowBackIos />,
  [IconType.Upload]: <CloudUploadOutlined />,
  [IconType.Done]: <CheckCircleOutline />,
  [IconType.Error]: <CancelOutlined />,
};
