export enum IconType {
  Home = 'Home',
  Groups = 'Groups',
  Messager = 'Messager',
  Help = 'Help',
  Settings = 'Settings',
  Notifications = 'Notifications',
  Arrow = 'Arrow',
  Views = 'Views',
  Send = 'Send',
  Email = 'Email',
  User = 'User',
  Lock = 'Lock',
  Exit = 'Exit',
  Like = 'Like',
  CloseArrow = 'CloseArrow',
}
